import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeSwitcher from "./components/ThemeSwitcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "zack/ari",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen flex flex-col`}>
        <header className="w-full bg-base-200 text-base-content p-4 pt-8 flex justify-between items-center z-20 relative" style={{ height: '60px' }}>
          <h1 className="text-xl font-bold">zack/ari</h1>
          <ThemeSwitcher />
        </header>
        <main className="bg-base-200 z-10 overflow-auto w-full">
          {children}
        </main>
      </body>
    </html>
  );
}
